if ~exist('discretized_system','var')
    error('comparison:missingDiscretizedSystem', ...
        'Variable ''discretized_system'' not found. Run main.m before this script.');
end

if ~exist('Hm_frd_smooth','var')
    error('comparison:missingMeasurement', ...
        ['Variable ''Hm_frd_smooth'' not found. Run frequency_response_identification ', ...
         'or load Hm_frd_deliverable_P_smooth.mat first.']);
end

wtest = 2*pi*[1 5 10 25 50 100];

P_model = squeeze(freqresp(discretized_system.Pz_zoh,wtest));
P_meas  = squeeze(freqresp(Hm_frd_smooth,wtest));

table(wtest(:)/(2*pi), ...
      20*log10(abs(P_model(:))), ...
      20*log10(abs(P_meas(:))), ...
      angle(P_model(:))*180/pi, ...
      angle(P_meas(:))*180/pi, ...
      'VariableNames',{'f_Hz','ModelMag_dB','MeasMag_dB','ModelPhase_deg','MeasPhase_deg'})
